/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TowersRouteImport } from './routes/towers'
import { Route as MinesRouteImport } from './routes/mines'
import { Route as CrashRouteImport } from './routes/crash'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'

const TowersRoute = TowersRouteImport.update({
  id: '/towers',
  path: '/towers',
  getParentRoute: () => rootRouteImport,
} as any)
const MinesRoute = MinesRouteImport.update({
  id: '/mines',
  path: '/mines',
  getParentRoute: () => rootRouteImport,
} as any)
const CrashRoute = CrashRouteImport.update({
  id: '/crash',
  path: '/crash',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/crash': typeof CrashRoute
  '/mines': typeof MinesRoute
  '/towers': typeof TowersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/crash': typeof CrashRoute
  '/mines': typeof MinesRoute
  '/towers': typeof TowersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/crash': typeof CrashRoute
  '/mines': typeof MinesRoute
  '/towers': typeof TowersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/admin' | '/crash' | '/mines' | '/towers'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/admin' | '/crash' | '/mines' | '/towers'
  id: '__root__' | '/' | '/admin' | '/crash' | '/mines' | '/towers'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  CrashRoute: typeof CrashRoute
  MinesRoute: typeof MinesRoute
  TowersRoute: typeof TowersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/towers': {
      id: '/towers'
      path: '/towers'
      fullPath: '/towers'
      preLoaderRoute: typeof TowersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mines': {
      id: '/mines'
      path: '/mines'
      fullPath: '/mines'
      preLoaderRoute: typeof MinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crash': {
      id: '/crash'
      path: '/crash'
      fullPath: '/crash'
      preLoaderRoute: typeof CrashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  CrashRoute: CrashRoute,
  MinesRoute: MinesRoute,
  TowersRoute: TowersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
